# Generated by Django 4.1.1 on 2024-01-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracker',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
