# Generated by Django 4.1.1 on 2024-01-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_tracker_amount_alter_tracker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='date',
            field=models.DateField(),
        ),
    ]
